### ISSUE TITLE
vnsee with vncserver: resolution and immediate stop

### ISSUE THREAD

**Issue by damienchallet** [matteodelabre/vnsee#17]
Since I cannot use the Intel solution and cannot make the generic alternative solution for virtual display work (vnsee crashes or continuously updates the screen for no reason), I am trying to use vnsee with a dedicated vncserver and then connect to it from the remarkable.

It start a (Tiger) vncserver with 

`vncserver -depth 16 -geometry 1408x3840 -SecurityTypes None :2`

First, why does vnsee ask for a 3840x1408 vncserver ?  

Then vnsee outputs "connected to [whatever server]" and immediately quits.

**Comment by matteodelabre** [comment]
Hi @damienchallet, thanks for the report and sorry for the delay.

> It start a (Tiger) vncserver with
> 
> `vncserver -depth 16 -geometry 1408x3840 -SecurityTypes None :2`

You should not need to set the `-depth 16` flag on the server, since the pixel format is automatically negotiated by the client.

> First, why does vnsee ask for a 3840x1408 vncserver ?

Does #11 answer your question?

> Then vnsee outputs "connected to [whatever server]" and immediately quits.

Could you please provide the server logs?

Thanks!

**Comment by mhhf** [comment]
@damienchallet as you are also using tigervnc and seem to have the same client side feedback, maybe #19 also solves your issue.

**Comment by damienchallet** [comment]
Hi @matteodelabre and @mhhf 

Thanks! The latest version solves the crash problem.

In addition, vnsee no longer asks for 3840 horizontal pixels.

Many thanks !
