### ISSUE TITLE
Problem connecting to android Termux

### ISSUE THREAD

**Issue by mhhf** [matteodelabre/vnsee#19]
I have problems connecting to my android phone.

After installing Termux app and tigervnc (together with aterm and xorg-twm) i can start a vnc server on my android phone with:
```
vncserver -localhost=0 -geometry 1408x1872 -pixelformat rgb565
```
and successfuly connect with other vnc clients. However, connecting with vnsee isn't working with the error on the server being thrown: `invalid pixel format`.

Have i missed something?

**Comment by matteodelabre** [comment]
Hi @mhhf, thanks for reporting! I did not test with TigerVNC before (only with x11vnc), but thanks to your report I noticed that I was missing setting the `depth` field in the pixel format request. It seems that x11vnc happily allows that this field is missing, but TigerVNC does not. Can you try the following `vnsee` build in which I added a fix to properly set that field? → [vnsee.zip](https://github.com/matteodelabre/vnsee/files/5866420/vnsee.zip)

**Comment by mhhf** [comment]
The new vnsee version works perfectly, without the `-pixelformat` flag! Thank you!

**Comment by matteodelabre** [comment]
Thanks for testing! I’ll publish a release including this fix shortly.
