### ISSUE TITLE
Client requires server screen size of 260x23936

### ISSUE THREAD

**Issue by bravech** [matteodelabre/vnsee#22]
I've tried installing both `rm2fb` and `vnsee` through toltec, as well as compiling both from source and scp'ing over, and I keep getting this same error. I also tried compiling from the `rm2-support` branch of the `vnsee` repo, to the same results. Same problem whether over wifi or over usb connection. 

Exact error message is: 
```Connecting to 10.11.99.3:5900...
terminate called after throwing an instance of 'std::runtime_error'
  what():  Server uses an unsupported resolution (1404x1872). This client can only cope with a screen width of exactly 260 pixels and a screen height of 23936 pixels
```

**Comment by bravech** [comment]
Duplicate of #15 
Turns out I wasn't running the dev build in the zip file provided. However, I'm still concerned if this should still be broken when running the `rm2-support` branch.

**Comment by matteodelabre** [comment]
Hi @bravech, could you please try again with [release 0.4.0](https://github.com/matteodelabre/vnsee/releases/tag/v0.4.0) to see if this still happens? Thanks!

**Comment by koenvervloesem** [comment]
I'm not OP, but installing rm2fb through toltec and the vnsee 0.4.0 binary from GitHub just worked on my reMarkable 2.

**Comment by matteodelabre** [comment]
That’s good to know, thanks @koenvervloesem! I’ll close this for now, please feel free to re-open the issue if you encounter the problem again @bravech.
