### ISSUE TITLE
Rebuild needed after remarkable1 update

### ISSUE THREAD

**Issue by twitwi** [matteodelabre/vnsee#23]
Thanks for the project.
I updated my remarkable yesterday and vnsee now fails due to updated SSL libraries.
libssl.so.1.0.2 -> libssl.so.1.1
....

It might be worth for users to make a new updated release.

**Comment by matteodelabre** [comment]
Thanks for reporting! I’ll look into it as soon as possible.

**Comment by static-void** [comment]
I also have this issue. Just when I figured out how to get an extra monitor output with nvidia too!

(BTW, might want to add to wiki: you can buy this dummy HDMI output thing https://www.amazon.co.uk/gp/product/B07YKGGQTJ/ and do:

``xrandr --output OUTPUTNAME --mode 1920x2160 --transform `bc -l <<< 1408/1920`,0,0,0,`bc -l <<< 1872/2160`,0,0,0,1 --pos XPOSxYPOS``

... this beats using xvfb and synergy/barrier any day)

**Comment by stevenbell** [comment]
Same here.  Also affects libcrypto (which I assume is tied to libssl).

Just making simlinks in /usr/lib didn't do the trick:
`./rmvncclient: /usr/lib/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by ./rmvncclient)`

**Comment by stevenbell** [comment]
I was able to get it working by just copying `libssl.so.1.0.2` and `libcrypto.so.1.0.2` into `/usr/lib` on the tablet.  I had these libraries from installing the (now out of date) dev tools from reMarkable, but there are other places you can get these files, e.g., https://github.com/bordaigorl/rmview/issues/57#issuecomment-808193006

This is obviously a temporary fix, but good enough for now!

**Comment by static-void** [comment]
Great work around @stevenbell. Here are the files, so just do
```unzip remarkable_libcrypto_libssl_1.0.2.zip
scp libcrypto.so.1.0.2 root@10.11.99.1:/usr/lib
scp libssl.so.1.0.2 root@10.11.99.1:/usr/lib```
[remarkable_libcrypto_libssl_1.0.2.zip](https://github.com/matteodelabre/vnsee/files/6267634/remarkable_libcrypto_libssl_1.0.2.zip)

**Comment by jfim** [comment]
In case you don't want to copy the libs in `/usr/lib` you can also extract them and run `vnsee` with `LD_LIBRARY_PATH=.`

In other words:
```
root@reMarkable:~# ls -1
libcrypto.so.1.0.2
libssl.so.1.0.2
remarkable_libcrypto_libssl_1.0.2.zip
vnsee

root@reMarkable:~# LD_LIBRARY_PATH=. ./vnsee
Connecting to 10.0.0.57:5900...
```

**Comment by matteodelabre** [comment]
Sorry for the delay. The build for [release 0.4.0](https://github.com/matteodelabre/vnsee/releases/tag/v0.4.0) works both on 2.5 and 2.6 (the latest rM update).

**Comment by twitwi** [comment]
Thanks a lot, both the workaround and now the new release worked.
