### ISSUE TITLE
Incompatible with 2.9 System Software

### ISSUE THREAD

**Issue by nullstalgia** [matteodelabre/vnsee#28]
Howdy

I downloaded the latest update on accident, and now I can't use vnsee.

It just gives me 

`Error: (rmioc::input) Get axis state: Invalid argument` constantly

Also, *please* add vnsee-gui to Draft so Draft and Remux can grab it without needing a terminal <3

**Comment by matteodelabre** [comment]
Hi! Are you on rM1 or rM2?

> Also, _please_ add vnsee-gui to Draft so Draft and Remux can grab it without needing a terminal <3

The Toltec package does install Draft and Oxide launcher files. I’d recommend installing VNSee from Toltec if you can. You can also install those files manually from <https://github.com/toltec-dev/toltec/tree/testing/package/vnsee>.

**Comment by nullstalgia** [comment]
Sorry, should have clarified. I'm on a reMarkable 1.

And hmm, I do have it from Toltec, but it was an older one and I tried to make my own. It's possible it I do have it, it's just not working due to the app also being broken, or something. I dunno.

I'll try to scrape every trace of vnsee clean in the meantime to rule out my own tinkering.

**Comment by matteodelabre** [comment]
Thanks for clarifying, I’m indeed able to reproduce your issue on my rM1. I’m working on a fix.

**Comment by matteodelabre** [comment]
@nullstalgia I added a fix on the master branch. From the testing I’ve done, this seems to work. Could you please test it on your device? Here’s a build, if needed: [vnsee-0.4.1.zip](https://github.com/matteodelabre/vnsee/files/7000101/vnsee-0.4.1.zip)

**Comment by nullstalgia** [comment]
VNSee itself seems to work now, good stuff! I was able to connect and view this thread on my monitor

![image](https://user-images.githubusercontent.com/20761757/129801229-847e208e-b032-463b-a252-960ab7a7538a.png)

The GUI also works, but it does not work when launched from remux (I don't use Draft, sorry).

Checking `systemctl status remux` after launching the GUI returned `Aug 17 20:49:44 reMarkable remux[611]: /opt/bin/vnsee-gui: line 114: HOME: unbound variable`

Replacing that with `/home/root/` doesn't just fix it, sadly.

But the GUI seems to fail to connect consistently, whether launched from Remux or via an extra SSH terminal. 

`timeout: 1` appears in the terminal almost instantly, and after a minute, it says it failed on the display.

**Comment by matteodelabre** [comment]
> VNSee itself seems to work now, good stuff! I was able to connect and view this thread on my monitor

Great! Thank you for testing it.

> The GUI also works, but it does not work when launched from remux (I don't use Draft, sorry).

Unfortunately I’ve not been able to reproduce this issue on my rM1. Did you install remux manually or from Toltec? Could you please share the result of `systemctl cat remux.service`? The unit definition from Toltec is the following (note the line that defines the HOME environment variable).

```ini
# Copyright (c) 2020 The Toltec Contributors
# SPDX-License-Identifier: MIT

[Unit]
Description=App launcher that supports multi-tasking applications
After=xochitl.service opt.mount
StartLimitInterval=30
StartLimitBurst=5
Conflicts=draft.service tarnish.service

[Service]
ExecStart=/opt/bin/remux
Restart=on-failure
RestartSec=5
Environment="HOME=/home/root"

[Install]
WantedBy=multi-user.target
```

**Comment by nullstalgia** [comment]
Hmm, mine is from Toltec. I guess it was never updated?? I re-installed remux when I redownloaded VNSee. Its possible that this was a manually made file.. Gonna wipe the file and reinstall remux and vnsee.

**Comment by nullstalgia** [comment]
So, remux can launch VNSee-gui now, but VNSee-gui can't connect *to WiFi-based VNC servers*, whether launched via a terminal or remux.

USB can connect fine, it seems. And I can connect to a WiFi server via SSH. I'll have to see if you have any extra args

**Comment by matteodelabre** [comment]
Great! So all your issues are fixed, if I understand correctly? For WiFi connection I admit that it’d be handy if it could detect available VNC servers on that interface, but scanning all addresses (which is what’s done for detecting servers on the USB interface) would be too long. I’ll have to look if there’s some smarter way to do it in the future.

**Comment by matteodelabre** [comment]
Good point, I just tested it on my local /24 network and it’s taking around 4 seconds. The approach you suggest with a manual scan button seems interesting. I’m moving this to a separate issue.

**Comment by matteodelabre** [comment]
Fixed in release 0.4.1.

**Comment by jbeard4** [comment]
Hi @matteodelabre, I wanted to report that I am getting this error in releases 0.3.1, downloaded through toltec, and 0.4.1, downloaded from Github and uploaded to the device via ssh, on RM1 firmware 2.9.1.236.

I would appreciate any insight you could share on this, and please let me know if there is anything I can do on my end to help diagnose this. 

Thank you.

**Comment by twdlup** [comment]
Hi all, anyone know if this works on the RPP? I just got mine, and I really want to try it as a VNC to remote into my Mac or iPad. It's on v3.20.0.87 assuming I may have to downgrade. If there are well-written instructions out there, on the downgrade, installation, please point me to them, I am a novice with Linux. **Many thanks!**
